services:
  - type: web
    name: clockinout-backend
    env: node
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CI
        value: false 